# Generated by Django 2.0.5 on 2018-08-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage='test', upload_to=''),
        ),
    ]
