# Generated by Django 2.0.5 on 2018-08-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0002_auto_20180815_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('references', models.TextField(max_length=15)),
                ('dependentOn', models.IntegerField(default=0)),
                ('number', models.IntegerField()),
                ('text', models.TextField(max_length=2000)),
                ('citedText', models.TextField(max_length=2000)),
                ('para', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
