# Generated by Django 2.0.5 on 2018-08-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0003_auto_20180816_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='claim',
            name='citedText',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='claim',
            name='dependentOn',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='claim',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='para',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='claim',
            name='references',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
