# Generated by Django 2.0.5 on 2018-08-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0006_auto_20180816_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='description',
            new_name='appNumber',
        ),
        migrations.AddField(
            model_name='claim',
            name='appNumber',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
