# Generated by Django 2.0.5 on 2018-08-17 18:31

import ADT.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0007_auto_20180817_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(blank=True, upload_to=ADT.models.File.only_filename),
        ),
    ]
