# Generated by Django 2.0.5 on 2018-08-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0008_auto_20180817_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
