# Generated by Django 2.0.5 on 2018-08-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0009_file_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
    ]
