# Generated by Django 2.0.5 on 2018-08-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0011_auto_20180820_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nothing',
        ),
    ]
