# Generated by Django 2.0.5 on 2018-08-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0014_auto_20180820_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
