# Generated by Django 2.0.5 on 2018-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0015_file_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='children',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='parents',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
