# Generated by Django 2.0.5 on 2018-08-24 18:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0016_auto_20180824_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='children',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
        migrations.AlterField(
            model_name='claim',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
    ]
