# Generated by Django 2.0.5 on 2018-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0017_auto_20180824_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='children',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='claim',
            name='parents',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
