# Generated by Django 2.0.5 on 2018-08-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADT', '0018_auto_20180824_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='ADT.Claim'),
        ),
    ]
